### ISSUE TITLE
Dashboard no longer works!

### ISSUE THREAD

**Issue by broncha** [resquebundle/resque#49]
Hi Phil!

In the docs you say
```
add __construct methods to inject your dependencies
```

But that breaks how `php-resque` instantiates jobs, and the dashboard no longer works.

```
Too few arguments to function App\MainBundle\Jobs\TrackerJob::__construct(), 0 passed in vendor/chrisboulton/php-resque/lib/Resque/Job/Factory.php on line 27 and exactly 2 expected
```

```
at src/MainBundle/Jobs/TrackerJob.php:38
  at App\MainBundle\Jobs\TrackerJob->__construct()
     (vendor/chrisboulton/php-resque/lib/Resque/Job/Factory.php:27)
```

Also do you have an example of a Job which is working for you in symfony 4, along with how you queue it?

**Comment by PhilETaylor** [comment]
Hey there @broncha 

Below is copy and pasted code from my live project (with some redactions, snips and reductions) to show how I'm injecting and using a service

What exact versions of resquebundle/resque and chrisboulton/php-resque do you have installed?

Your error message leads me to believe that your Job's are not being loaded in Symfony as a service. To do that you need to ensure that your jobs are in your services.yml file, for some reason, on checking for you now, I see that mine are specifically called and are public too...

services.yml  snippet is
```yml
services:
  _defaults:
    autowire: true
    autoconfigure: true
  MyJoomlaWorker\:
    resource: '../src/MyJoomlaWorker/*'
    exclude: '../src/MyJoomlaWorker/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
  MyJoomlaWorker\Job\:
    public: true
    resource: '../src/MyJoomlaWorker/Job/*'
```

Here is the job class

```php
<?php
/*
* // snip
*/

namespace MyJoomlaWorker\Job;

use Doctrine\Common\Persistence\ManagerRegistry;
use ErrorException;
use Exception;
use ResqueBundle\Resque\Job;

/**
 * Class myJob.
 */
class myJob extends Job
{
    /**
     * @var string The queue name
     */
    public $queue = 'thequeuenametouse';

    /**
     * @var ManagerRegistry
     */
    private $registry;

    /**
      * @param array $args
     */
    public function __construct($args = [], ManagerRegistry $registry)
    {
        $this->registry = $registry;
        parent::__construct($args);
    }

    /**
     * @param array $args
     */
    public function run($args = [])
    {
        $entityManager = $this->registry->getManager();
        // snip - do something here... 
    }
}
```


Hope this helps,
